package telecardio;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 *
 * @author tiavr
 */
public class PropositionDossier extends javax.swing.JFrame {

    private ServeurTelecardiolSansSW serveur;
    private int numDossier;
    /**
     * Creates new form PropositionDossier
     */
    public PropositionDossier(ServeurTelecardiolSansSW serveur, int numDossier) {
        initComponents();
        this.numDossier = numDossier;
        this.serveur = serveur;
        JFrame frame = new JFrame();
        frame.setLayout(null);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.add(jPanel1);
        frame.add(jPanel2);
        frame.pack();
        frame.setVisible(true);

        for(DossierExpertise dossier : serveur.getListeAttente()){
            if(dossier.getNumero() == numDossier){
                numeroDossier.setText((String.valueOf(numDossier)));
                nomPatient.setText(dossier.getPatient());
                nomGeneraliste.setText(dossier.getGeneraliste());
                signesCliniques.setText(dossier.getSignes());
                jPanelEcg1.setEcg(dossier.getEcg());
            }
        }

    }

    public PropositionDossier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jLabel8 = new JLabel();
        numeroDossier = new JTextField();
        nomPatient = new JTextField();
        nomGeneraliste = new JTextField();
        signesCliniques = new JTextField();
        refuserButton = new JButton();
        avisButton = new JButton();
        antecedentButton = new JButton();
        jPanelEcg1 = new JPanelEcg();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jPanel2 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(188, 223, 191));

        jLabel8.setBackground(new Color(226, 248, 210));
        jLabel8.setForeground(new Color(0, 0, 0));

        numeroDossier.setEditable(false);
        numeroDossier.setBackground(new Color(255, 255, 255));
        numeroDossier.setForeground(new Color(0, 0, 0));
        numeroDossier.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                numDossierActionPerformed(evt);
            }
        });

        nomPatient.setEditable(false);
        nomPatient.setBackground(new Color(255, 255, 255));
        nomPatient.setForeground(new Color(0, 0, 0));

        nomGeneraliste.setEditable(false);
        nomGeneraliste.setBackground(new Color(255, 255, 255));
        nomGeneraliste.setForeground(new Color(0, 0, 0));

        signesCliniques.setEditable(false);
        signesCliniques.setBackground(new Color(255, 255, 255));
        signesCliniques.setForeground(new Color(0, 0, 0));
        signesCliniques.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                signesCliniquesActionPerformed(evt);
            }
        });

        refuserButton.setBackground(new Color(204, 0, 0));
        refuserButton.setText("Refuser");
        refuserButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                refuserButtonActionPerformed(evt);
            }
        });

        avisButton.setBackground(new Color(255, 255, 204));
        avisButton.setForeground(new Color(0, 0, 0));
        avisButton.setText("Rédiger un avis");
        avisButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                avisButtonActionPerformed(evt);
            }
        });

        antecedentButton.setText("Antécédents Patient");
        antecedentButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                antecedentButtonActionPerformed(evt);
            }
        });

        GroupLayout jPanelEcg1Layout = new GroupLayout(jPanelEcg1);
        jPanelEcg1.setLayout(jPanelEcg1Layout);
        jPanelEcg1Layout.setHorizontalGroup(
            jPanelEcg1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanelEcg1Layout.setVerticalGroup(
            jPanelEcg1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel3.setFont(new Font("DejaVu Sans Mono", 0, 16)); // NOI18N
        jLabel3.setForeground(new Color(0, 0, 0));
        jLabel3.setText("Dossier n°:");

        jLabel4.setFont(new Font("DejaVu Sans Mono", 0, 16)); // NOI18N
        jLabel4.setForeground(new Color(0, 0, 0));
        jLabel4.setText("Patient:");

        jLabel5.setFont(new Font("DejaVu Sans Mono", 0, 16)); // NOI18N
        jLabel5.setForeground(new Color(0, 0, 0));
        jLabel5.setText("Medecin Généraliste:");

        jLabel6.setFont(new Font("DejaVu Sans Mono", 0, 16)); // NOI18N
        jLabel6.setForeground(new Color(0, 0, 0));
        jLabel6.setText("Signes cliniques:");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nomGeneraliste, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(nomPatient)
                    .addComponent(numeroDossier)
                    .addComponent(signesCliniques))
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jPanelEcg1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(avisButton)
                        .addGap(42, 42, 42)))
                .addGap(45, 45, 45))
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refuserButton, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(antecedentButton)
                    .addContainerGap(540, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(numeroDossier, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(nomPatient, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(nomGeneraliste, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelEcg1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(avisButton)
                        .addGap(10, 10, 10)))
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(signesCliniques, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(refuserButton)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(382, Short.MAX_VALUE)
                    .addComponent(antecedentButton)
                    .addGap(19, 19, 19)))
        );

        jPanel2.setBackground(new Color(226, 248, 210));

        jLabel1.setFont(new Font("DejaVu Sans Mono", 1, 24)); // NOI18N
        jLabel1.setForeground(new Color(0, 0, 0));
        jLabel1.setText("Système TéléCardio");

        jLabel2.setFont(new Font("DejaVu Sans Mono", 1, 24)); // NOI18N
        jLabel2.setForeground(new Color(0, 0, 0));
        jLabel2.setText("Interface Spécialiste");

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(177, 177, 177)
                    .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(178, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numDossierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numDossierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numDossierActionPerformed

    private void signesCliniquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signesCliniquesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signesCliniquesActionPerformed

    private void avisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avisButtonActionPerformed
        // TODO add your handling code here:
        new RedactionAvis(serveur, numDossier).setVisible(true);
    }//GEN-LAST:event_avisButtonActionPerformed

    private void antecedentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antecedentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_antecedentButtonActionPerformed

    private void refuserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refuserButtonActionPerformed
        serveur.refuserDossier(numDossier);
        new SpecialisteAccueil(serveur).setVisible(true);

    }//GEN-LAST:event_refuserButtonActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //* Set the Nimbus look and feel *//*
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        //* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PropositionDossier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PropositionDossier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PropositionDossier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PropositionDossier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //* Create and display the form *//*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PropositionDossier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton antecedentButton;
    private javax.swing.JButton avisButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private telecardio.JPanelEcg jPanelEcg1;
    private javax.swing.JTextField nomGeneraliste;
    private javax.swing.JTextField nomPatient;
    private javax.swing.JTextField numeroDossier;
    private javax.swing.JButton refuserButton;
    private javax.swing.JTextField signesCliniques;
    // End of variables declaration//GEN-END:variables
}
